language: python
python:
  - "3.7"

before_script:
  - pip install -r requirements.txt

script:
  - python app/manage.py makemigrations
  - python app/manage.py test recipe
  - python app/manage.py test core
