version: '3.7'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - /d/Projects/digital-cookbook-backend/app:/app
    command: >
      sh -c "ls -alt && python manage.py wait_for_db &&
            python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_PASSWORD=PASSWORD123
      - DB_USER=postgres
    depends_on:
      - db

  db:
    image: postgres:12.2-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_PASSWORD=PASSWORD123
      - POSTGRES_USER=postgres
